rvm:
  - 1.9.3
 
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/app
  matrix:
    - BUILD_CMD='rspec'
    - BUILD_CMD='rake assets:precompile RAILS_ENV=production'
    - BUILD_CMD='rake db:setup RAILS_ENV=development'
 
before_script:
  - bundle exec rake db:create db:migrate
 
script: eval bundle exec ${BUILD_CMD}